---
- name: AS3 delpoyment test
  hosts: localhost
  connection: local
  gather_facts: false


  vars:
S

  vars_files:
    - ../credentials/bigip_certs.yaml

  tasks:

    - name: Deploys as3 declaration
      uri:
        url: https://51.142.10.142:8443/mgmt/shared/appsvcs/declare/
        user: "{{username}}"
        password: "{{password}}"
        method: POST
        body: "{{ lookup('file','as3.json') }}"
        force_basic_auth: true
        status_code: 200
        body_format: json
        validate_certs: false
      register: as3_output

    - name: AS3 output
      debug:
        var: as3_output.json.declaration.id

...